---
- hosts: all
  gather_facts: false

  tasks:
    - name: install PostgreSQL
      become: true
      apt:
        name: "postgresql"
        state: present

    - name: enable and start postgres service
      service:
        name: "postgresql"
        enabled: true
        state: started

    - name: copy PostgreSQL config file
      become: true
      copy:
        src: "{{ item }}"
        dest: /etc/postgresql/9.5/main/
        owner: postgres
        group: postgres
      with_items:
        - "postgresql.conf"
        - "pg_hba.conf"

    - name: restart postgres service
      become: true
      service:
        name: "postgresql"
        state: restarted

    - name: create vagrant user and database
      become: true
      become_user: "postgres"
      shell: |
        psql --command "DROP DATABASE IF EXISTS vagrant;"
        psql --command "DROP USER IF EXISTS vagrant;"
        psql --command "CREATE USER vagrant WITH PASSWORD 'vagrant';"
        psql --command "CREATE DATABASE vagrant WITH ENCODING 'UTF-8' LC_COLLATE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8' OWNER = vagrant;"
        psql --command "GRANT ALL ON DATABASE vagrant TO vagrant;"
      args:
        executable: /bin/bash
